# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-26 17:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tweet_id', models.BigIntegerField(db_index=True)),
                ('text', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('place', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('retweet_count', models.BigIntegerField(blank=True, default=None, null=True)),
                ('favorite_count', models.BigIntegerField(blank=True, default=None, null=True)),
                ('raw_response', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('twitter_id', models.BigIntegerField(db_index=True)),
                ('screen_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('profile_picture', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('time_zone', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('followers_count', models.BigIntegerField(blank=True, default=None, null=True)),
                ('friends_count', models.BigIntegerField(blank=True, default=None, null=True)),
                ('url', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('raw_response', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apple.TwitterUser'),
        ),
    ]
