# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-27 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0002_auto_20180327_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='sentiment',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
