# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-28 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0003_tweet_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='place',
            field=models.TextField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='profile_picture',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='screen_name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='url',
            field=models.TextField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
