# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-02 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0005_auto_20180331_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='priority',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
