# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-07 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0007_tweet_resolved_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
