# Generated by Django 2.0.5 on 2018-10-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0009_twitteruser_following_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(on_delete='cascade', to='apple.TwitterUser'),
        ),
    ]
